### ISSUE TITLE
First Launch after install fails: IO Exception writing client-intermediary.jar.tmp on Portable/RAMDrive, successful write on 'physicaldisk'; moving completed client-intermediary.jar to Portable/RAMDrive runs fine.

### ISSUE THREAD

**Issue by Shaggygoblin** [FabricMC/tiny-remapper#102]
I have 128GB RAM.
I have Minecraft (16 GB RD) and other games, like Subnautica+BZ (32GB RD), Transport Fever 2 (32GB RD), Kerbal Space Program (16 GB RD) installed on RAMDrives (RD) using ImDisk.
Minecraft runs great; vanilla, setup as a portable install.  Subnautica and Subnautic: Below Zero are amazingly fast.  Loading TPF2 is a flash and zipping around the map is hitchless.  Kerbal Space Program has no stuttering when loading in new bodies.

Trying to install Fabric, not so much.
I get an IO Exception writing to client-intermediary.jar.tmp.

Moving the install to a folder on the desktop (as a portable install), and then running the first launch (to do the remapping) works and I get straight to the Main Menu afterward.

Then I move the good client-intermediary.jar back to the correct spot on the RAMDrive.
Launch again from the RAMDrive...straight to Main Menu.

There is a failure at the remapping thing, and I suspect it's due to some way it's trying to access the file.
Almost like it's using some way-too-fancy hardware-level storage access to do the read/write instead of sticking to the known-working filesystem/path-level access that the parent, launcher/minecraft, uses (even with the anal-ity of the Microsoft Account / Xbox GamePass ~~bullshit~~ crap).
The RAMDisk is known for not being accessible with hardware-level I/O functions.  Everything else, which only uses filesystem/path-level read/write works a peach.  (Yes, I'm aware there are offerings that create a iSCSI interface for the RAMDisk, but they're too small, or do not support sync and/or mount at boot.  Also, the few which do offer this, want a premium for function that, frankly, should have been added into the OS when M$ had their own [driver sample](https://en.wikipedia.org/wiki/List_of_RAM_drive_software#Microsoft_source_code))

Some of [these issues](https://github.com/FabricMC/fabric-loader/issues?q=Uncaught+exception+in+thread+%22main%22) appear to be a close match, but not 'duplicate' of my issue.

FWIW:
I built my Portable Minecraft using the steps outlined in these two wiki pages:
[Tutorials/Playing and saving Minecraft on a thumb drive](https://minecraft.fandom.com/wiki/Tutorials/Playing_and_saving_Minecraft_on_a_thumb_drive)
[Tutorials/Playing and saving Minecraft on a thumb drive with the old launcher](https://minecraft.fandom.com/wiki/Tutorials/Playing_and_saving_Minecraft_on_a_thumb_drive_with_the_old_launcher)

My launcher batch (Modded_1.19.2.bat):
`@echo off
set APPDATA="M:\Data_1.19.2"
start "" "M:\Launcher\Minecraft.exe" --workDir "M:\Modded_1.19.2"`

If you want a log from it running first/second launch from RAMDrive:

First launch [fabricloader.log](https://github.com/FabricMC/tiny-remapper/files/9793324/fabricloader.log)

first launch launcher_log.txt
Line# 1964 - 2013
> [Info: 2022-10-15 23:33:59.8658530: GameCallbacks.cpp(228)] Launcher/launcher (main) Info [18:33:40] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
> 
> [18:33:40] [INFO] [FabricLoader/GameRemap]: Fabric is preparing JARs on first launch, this may take a few seconds...
> 
> [18:33:41] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
> 
> java.lang.RuntimeException: error remapping game jars [<APPDIR>\Modded_1.19.2\versions\fabric-loader-0.14.9-1.19.2\fabric-loader-0.14.9-1.19.2.jar]
> 
> 	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:240)
> 
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:313)
> 
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
> 
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> Caused by: java.io.IOException: the jar file <APPDIR>\Modded_1.19.2\.fabric\remappedJars\minecraft-1.19.2-0.14.9\client-intermediary.jar.tmp can't be written
> 
> 	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:114)
> 
> 	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:47)
> 
> 	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:76)
> 
> 	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:294)
> 
> 	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:238)
> 
> 	... 4 more
> 
> 
> [Info: 2022-10-15 23:33:59.8659310: GameCallbacks.cpp(228)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code 1
> [Info: 2022-10-15 23:33:59.8666141: GameController.cpp(536)] Game closed with id 1
> [Info: 2022-10-15 23:33:59.8668045: NetQueue.cpp(695)] NetQueue: Starting net action http://hopper.minecraft.net/crashes/submit_report/
> [Info: 2022-10-15 23:33:59.8896084: LauncherAppRenderer.cpp(290)] MCLauncher.triggerUpdateEvent("coreEvent.gameInstances");
> [Info: 2022-10-15 23:33:59.8950931: LauncherAppRenderer.cpp(290)] MCLauncher.triggerUpdateEvent("coreEvent.gameInstances");
> [Info: 2022-10-15 23:33:59.9965490: NetQueue.cpp(484)] NetQueue: Primary ip: 35.168.97.233, Host: hopper.minecraft.net
> [Info: 2022-10-15 23:33:59.9966021: NetQueue.cpp(573)] NetQueue: Action finished: http://hopper.minecraft.net/crashes/submit_report/
> [Info: 2022-10-15 23:33:59.9967179: GameCallbacks.cpp(90)] Destroying GameCallbacks!
> [Info: 2022-10-15 23:33:59.9967549: Process_Windows.cpp(76)] Exiting process <APPDIR>\...\javaw.exe
> [Info: 2022-10-15 23:33:59.9967854: Process_Windows.cpp(80)] Joining stdout thread
> [Warning: 2022-10-15 23:33:59.9968037: Process_Windows.cpp(82)] The io_service is still running work so signal it to stop..
> [Info: 2022-10-15 23:33:59.9970426: Process_Windows.cpp(86)] Joined!
> [Info: 2022-10-15 23:33:59.9978114: client_handler.cpp(852)] NotifyBrowserClosing
> [Info: 2022-10-15 23:33:59.9979796: browser_window.cpp(61)] OnBrowserClosing
> [Info: 2022-10-15 23:34:00.0093021: client_handler.cpp(881)] NotifyBrowserClosed
> [Info: 2022-10-15 23:34:00.0093549: browser_window.cpp(68)] OnBrowserClosed (with delegate)
> [Info: 2022-10-15 23:34:00.0103570: root_window_manager.cpp(303)] Main window has been closed: 0D147548

Second launch [fabricloader.log](https://github.com/FabricMC/tiny-remapper/files/9793375/fabricloader.log)

Second launch launcher_log.txt
line# 2044 - 2095

> [Info: 2022-10-16 00:30:39.3334305: GameCallbacks.cpp(228)] Launcher/launcher (main) Info [19:30:12] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
> 
> [19:30:13] [WARN] [FabricLoader/GameRemap]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
> 
> [19:30:13] [INFO] [FabricLoader/GameRemap]: Fabric is preparing JARs on first launch, this may take a few seconds...
> 
> [19:30:14] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
> 
> java.lang.RuntimeException: error remapping game jars [<APPDIR>\Modded_1.19.2\versions\fabric-loader-0.14.9-1.19.2\fabric-loader-0.14.9-1.19.2.jar]
> 
> 	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:240)
> 
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:313)
> 
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
> 
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> Caused by: java.io.IOException: the jar file <APPDIR>\Modded_1.19.2\.fabric\remappedJars\minecraft-1.19.2-0.14.9\client-intermediary.jar.tmp can't be written
> 
> 	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:114)
> 
> 	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:47)
> 
> 	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:76)
> 
> 	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:294)
> 
> 	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:238)
> 
> 	... 4 more
> 
> 
> [Info: 2022-10-16 00:30:39.3335129: GameCallbacks.cpp(228)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code 1
> [Info: 2022-10-16 00:30:39.3342476: GameController.cpp(536)] Game closed with id 1
> [Info: 2022-10-16 00:30:39.3345359: NetQueue.cpp(695)] NetQueue: Starting net action http://hopper.minecraft.net/crashes/submit_report/
> [Info: 2022-10-16 00:30:39.3661841: LauncherAppRenderer.cpp(290)] MCLauncher.triggerUpdateEvent("coreEvent.gameInstances");
> [Info: 2022-10-16 00:30:39.3727486: LauncherAppRenderer.cpp(290)] MCLauncher.triggerUpdateEvent("coreEvent.gameInstances");
> [Info: 2022-10-16 00:30:39.4475289: NetQueue.cpp(484)] NetQueue: Primary ip: 35.168.97.233, Host: hopper.minecraft.net
> [Info: 2022-10-16 00:30:39.4475968: NetQueue.cpp(573)] NetQueue: Action finished: http://hopper.minecraft.net/crashes/submit_report/
> [Info: 2022-10-16 00:30:39.4477062: GameCallbacks.cpp(90)] Destroying GameCallbacks!
> [Info: 2022-10-16 00:30:39.4477479: Process_Windows.cpp(76)] Exiting process <APPDIR>\...\javaw.exe
> [Info: 2022-10-16 00:30:39.4477820: Process_Windows.cpp(80)] Joining stdout thread
> [Warning: 2022-10-16 00:30:39.4478048: Process_Windows.cpp(82)] The io_service is still running work so signal it to stop..
> [Info: 2022-10-16 00:30:39.4480715: Process_Windows.cpp(86)] Joined!
> [Info: 2022-10-16 00:30:39.4493631: client_handler.cpp(852)] NotifyBrowserClosing
> [Info: 2022-10-16 00:30:39.4495777: browser_window.cpp(61)] OnBrowserClosing
> [Info: 2022-10-16 00:30:39.4572421: client_handler.cpp(881)] NotifyBrowserClosed
> [Info: 2022-10-16 00:30:39.4573043: browser_window.cpp(68)] OnBrowserClosed (with delegate)
> [Info: 2022-10-16 00:30:39.4585616: root_window_manager.cpp(303)] Main window has been closed: 0D4CCB18

Move stuff to 'physical disk':

(Modify the .bat):
`@echo off
set APPDATA="C:\Users\Daddy\Desktop\Minecraft_Portable\Data_1.19.2"
start "" "C:\Users\Daddy\Desktop\Minecraft_Portable\Launcher\Minecraft.exe" --workDir "C:\Users\Daddy\Desktop\Minecraft_Portable\Modded_1.19.2"`

Set Game Directory for Fabric in Launcher to: "C:\Users\Daddy\Desktop\Minecraft_Portable\Modded_1.19.2"

Here's what I get when running it from the Desktop:

Physical disk first launch [latest.log](https://github.com/FabricMC/tiny-remapper/files/9793406/latest.log)

launcher_log.txt
Line# 2055 - 2066

> [Info: 2022-10-16 01:01:36.1090373: GameCallbacks.cpp(228)] Game/FabricLoader/GameProvider (main) Info Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
> [Info: 2022-10-16 01:01:36.1109316: GameCallbacks.cpp(228)] Game/FabricLoader/GameRemap (main) Warn Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
> [Info: 2022-10-16 01:01:36.1110666: GameCallbacks.cpp(228)] Game/FabricLoader/GameRemap (main) Info Fabric is preparing JARs on first launch, this may take a few seconds...
> [Info: 2022-10-16 01:01:36.5147218: GameCallbacks.cpp(228)] Game/FabricLoader (main) Info Loading 3 mods:
> 	- fabricloader 0.14.9
> 	- java 17
> 	- minecraft 1.19.2
> [Info: 2022-10-16 01:01:36.6133667: GameCallbacks.cpp(228)] Game/FabricLoader/Mixin (main) Info SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Daddy/Desktop/Minecraft_Portable/Modded_1.19.2/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
> [Info: 2022-10-16 01:01:37.5477517: GameCallbacks.cpp(228)] Game/oshi.util.FileUtil (main) Warn Configuration conflict: there is more than one oshi.properties file on the classpath
> [Info: 2022-10-16 01:01:38.1402609: GameCallbacks.cpp(228)] Game/oshi.util.FileUtil (main) Warn Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
> [Info: 2022-10-16 01:01:38.5338245: GameCallbacks.cpp(228)] Game/oshi.util.platform.windows.PerfDataUtil (main) Warn Failed to update counter. Error code: 0x800007D5
> [Info: 2022-10-16 01:01:38.5341314: GameCallbacks.cpp(228)] Game/oshi.util.platform.windows.PerfCounterQuery (main) Warn Disabling further attempts to query Paging File.

Now I have (RAMDRive)"M:\Modded_1.19.2\.fabric\remappedJars\minecraft-1.19.2-0.14.9\client-intermediary.jar.tmp"
[client-intermediary.jar.tmp.zip](https://github.com/FabricMC/tiny-remapper/files/9793419/client-intermediary.jar.tmp.zip)

And (Physical disk)"C:\Users\Daddy\Desktop\Minecraft_Portable\Modded_1.19.2\.fabric\remappedJars\minecraft-1.19.2-0.14.9\client-intermediary.jar"
[client-intermediary.jar.zip](https://github.com/FabricMC/tiny-remapper/files/9793420/client-intermediary.jar.zip)

I take the new client-intermediary.jar from the physical disk, and place it in the RAMDisk at client-intermediary.jar.tmp, and delete the .tmp.

Run the .bat from the RAMDrive one final time nets me the following logs:

[latest.log](https://github.com/FabricMC/tiny-remapper/files/9793455/latest.log)

launcher_log.txt
Line# 1392 - 1397

> [Info: 2022-10-16 01:41:10.0989737: GameCallbacks.cpp(228)] Launcher/launcher (main) Info Minecraft client fabric-loader-0.14.9-1.19.2 is ready to start.
> [Info: 2022-10-16 01:41:10.0990318: GameController.cpp(489)] Starting game with token 1
> [Info: 2022-10-16 01:41:10.0990540: GameCallbacks.cpp(228)] Launcher/launcher (main) Info Starting!
> [Info: 2022-10-16 01:41:10.0991198: GameCallbacks.cpp(228)] Launcher/launcher (main) Debug Nothing to download!
> [Info: 2022-10-16 01:41:10.0991591: GameCallbacks.cpp(228)] Launcher/launcher (main) Debug Downloading Java Runtime java-runtime-gamma:17.0.3
> [Info: 2022-10-16 01:41:10.0998580: PistonInstaller.cpp(333)] Inspecting files in <APPDIR>\...\java-runtime-gamma

And more importantly, a working Fabric install on the RAMDrive.

I can't find it again, but read somewhere when looking for info on this crash, that when sending the log(s), some info in them is 'sensitive' and should be redacted/obfuscated.  If full launcher_log.txt's are needed, please let me know what needs scrubbed in them.

**Comment by amolinarius** [comment]
Any updates on this? Still not working for me, even when using a symlink in the %appdata%/.minecraft
