### ISSUE TITLE
RuntimeException: Failed to remap minecraft (IllegalArgumentException)

### ISSUE THREAD

**Issue by AlexProgrammerDE** [FabricMC/tiny-remapper#48]
HI! I got an issue when trying to do almost anything in my project:
```java
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'PistonClient'.
Caused by: java.lang.RuntimeException: Failed to provide net.fabricmc:yarn:1.16.5+build.5 : java.lang.RuntimeException: Failed to remap minecraft
	at net.fabricmc.loom.configuration.LoomDependencyManager.handleDependencies(LoomDependencyManager.java:133)
	at net.fabricmc.loom.configuration.CompileConfiguration.lambda$configureCompile$12(CompileConfiguration.java:168)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:152)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
Caused by: java.lang.RuntimeException: Failed to remap minecraft
	at net.fabricmc.loom.configuration.providers.minecraft.MinecraftMappedProvider.provide(MinecraftMappedProvider.java:89)
	at net.fabricmc.loom.configuration.providers.mappings.MappingsProvider.provide(MappingsProvider.java:175)
	at net.fabricmc.loom.configuration.LoomDependencyManager.handleDependencies(LoomDependencyManager.java:131)
	... 138 more
Caused by: java.lang.RuntimeException: Failed to remap JAR C:\Users\alex-\.gradle\caches\fabric-loom\minecraft-1.16.5-merged.jar with mappings from C:\Users\alex-\.gradle\caches\fabric-loom\mappings\yarn-1.16.5+build.5-v2.tiny
	at net.fabricmc.loom.configuration.providers.minecraft.MinecraftMappedProvider.mapMinecraftJar(MinecraftMappedProvider.java:122)
	at net.fabricmc.loom.configuration.providers.minecraft.MinecraftMappedProvider.provide(MinecraftMappedProvider.java:83)
	... 140 more
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:75)
	at net.fabricmc.tinyremapper.TinyRemapper$3.<init>(TinyRemapper.java:429)
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:429)
	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:65)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:411)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:407)
	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:407)
	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:65)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:376)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:372)
```
I cut the stack trace a bit because it had like 200 internal calls.  I am not sure how to go about this and in the discord no one responded to me either or knew a solution. How can I fix this bug?

**Comment by modmuss50** [comment]
What version of loom is this? I assume 0.5? It should have been fixed in 0.6. Can you please check? If so I can look at backporting the fix to 0.5.

**Comment by AlexProgrammerDE** [comment]
> What version of loom is this? I assume 0.5? It should have been fixed in 0.6. Can you please check? If so I can look at backporting the fix to 0.5.

I am using `0.6-SNAPSHOT` so I guess it may be something with the recent builds? My IDE can't resolve `0.5-SNAPSHOT` for some reason. Pretty much anything isn't found except `0.6-SNAPSHOT`

**Comment by modmuss50** [comment]
Can you post your build.gradle file? Do you have any additional plugins?

**Comment by AlexProgrammerDE** [comment]
@modmuss50 
```gradle
plugins {
    id 'fabric-loom' version '0.6-SNAPSHOT'
    id 'maven-publish'
    id 'java'
    id "com.github.gradle-lean" version "0.1.2"
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
    maven {
        name = "CottonMC"
        url = "https://server.bbkr.space/artifactory/libs-release"
    }
    maven {
        name = "jitpack"
        url = 'https://jitpack.io'
    }
    maven {
        name = 'lukflug'
        url = 'https://lukflug.github.io/maven'
    }
    maven {
        name = 'multiconnect'
        url = 'https://dl.bintray.com/earthcomputer/mods'
    }
    maven {
        name = 'sponge-repo'
        url = 'https://repo.spongepowered.org/maven'
    }
    jcenter()
}

dependencies {
    //to change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation 'net.earthcomputer:multiconnect:1.3.34:api'
    compile 'com.lukflug:panelstudio:0.1.8'
    include 'net.earthcomputer:multiconnect:1.3.34:api'

    implementation 'com.github.JnCrMx:discord-game-sdk4j:v0.5'
    implementation 'com.lukflug:panelstudio-mc16:0.1.9'
    implementation 'me.xdrop:fuzzywuzzy:1.3.1'

    implementation 'com.github.TerraformersMC:ModMenu:v1.16.5'
    modRuntime 'net.earthcomputer:multiconnect:1.3.34:slim'

    // PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
    // You may need to force-disable transitiveness on them.
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            // add all the jars that should be included when publishing to maven
            artifact(remapJar) {
                builtBy remapJar
            }
            artifact(sourcesJar) {
                builtBy remapSourcesJar
            }
        }
    }

    // Select the repositories you want to publish to
    // To publish to maven local, no extra repositories are necessary. Just use the task `publishToMavenLocal`.
    repositories {
        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    }
}
```

**Comment by zml2008** [comment]
https://github.com/cuzfrog/gradle-lean is probably bringing in an outdated asm dependency. unsure why you're bringing it in, since you're not even using the application plugin, which is the only thing it's designed to work with.

**Comment by AlexProgrammerDE** [comment]
hm now i get this:
```java
> Task :runClient
[08:52:25] [main/INFO] (FabricLoader) Loading for game Minecraft 1.16.5
[08:52:26] [main/FATAL] (Fabric|Loader) A critical error occurred
 net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'fabricloader': [0.11.2 at /C:/Users/alex-/Desktop/PistonClient/.gradle/loom-cache/remapped_mods/net_fabricmc_yarn_1_16_5_1_16_5_build_5_v2/net/fabricmc/fabric-loader/0.11.2/fabric-loader-0.11.2.jar], [0.11.1 at /C:/Users/alex-/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.11.1/d944def3134aa24883896b3a7741a0b4741a7b6b/fabric-loader-0.11.1.jar]
	at net.fabricmc.loader.discovery.ModCandidateSet.toSortedSet(ModCandidateSet.java:89) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:101) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```
I got a lot of different errors before that I somehow resolved. Firstly I was in "gradle offline mode"? Sounded weird. Then It told me  that file hashed didn't match. Now I get this, and I already tried resetting my .gradle, but it seems to come back.

**Comment by Technici4n** [comment]
Can you try `gradlew clean runClient`?

**Comment by AlexProgrammerDE** [comment]
nope. Still the sane.

**Comment by zml2008** [comment]
so, another guess here: You might be pulling some mod dependencies in under a non-`mod*` configuration. I see modmenu at least, perhaps some of the others that I don't recognize. That would be a way you could end up with two different copies of loader on the classpath.

(also -- I believe modmenu is on an actual maven repo, maybe even fabric's itself, jitpack should be avoided where possible)

**Comment by Technici4n** [comment]
Oh, good catch. Yes, you should be using `modImplementation` and `modCompileOnly` :)

**Comment by AlexProgrammerDE** [comment]
That fixed it! Thanks! <3
