### ISSUE TITLE
Illegal access error when using remapped jar

### ISSUE THREAD

**Issue by Bixilon** [FabricMC/tiny-remapper#49]
Hi there,
I am remapping the jar with first to intermediary then to named (yarn mappings). 

I use the following parameters: `--renameinvalidlocals --rebuildsourcefilenames --resolvemissing --fixpackageaccess --checkpackageaccess`

When simply calling ` Bootstrap.initialize()`, I get the following exception:

```
Exception in thread "main" java.lang.IllegalAccessError: class net.minecraft.class_2281$1 cannot access its superinterface net.minecraft.block.ChestBlock$PropertyRetriever
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.block.ChestBlock.<clinit>(ChestBlock.java:243)
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:167)
	at net.minecraft.util.registry.Registry.method_10237(Registry.java:81)
	at net.minecraft.util.registry.Registry.method_10238(Registry.java:125)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:124)
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:38)
	at de.bixilon.pixlyzer.PixLyzer.main(PixLyzer.kt:69)

Process finished with exit code 1
```

I had similar issues in the newest snapshot, e.g. when making EntityType::spawn. But in the newer snapshot I get a VerifyError (sorry, not happening anymore, idk why), but I could workaround it with `-Xverify:none`. But we all know this JVM parameter and how many recommendations it has.

Simply: How to make it work? I also tried other start parameters, but they didn't helped. Is it a bug or am I doing something wrong?

Thanks

# Edit: Using 19w46b

**Comment by Bixilon** [comment]
Here is the exception in the newest snapshot without `-xverify:none`.

```

Exception in thread "main" java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    net/minecraft/class_6331.method_36215(Lnet/minecraft/world/gen/carver/Carver;Lnet/minecraft/world/chunk/Chunk;Ljava/util/Random;Lnet/minecraft/util/math/BlockPos$Mutable;Lnet/minecraft/util/math/BlockPos$Mutable;I)Z @23: invokevirtual
  Reason:
    Type 'net/minecraft/world/gen/carver/Carver' (current frame, stack[0]) is not assignable to 'net/minecraft/class_6331'
  Current Frame:
    bci: @23
    flags: { }
    locals: { 'net/minecraft/world/gen/carver/Carver', 'net/minecraft/world/chunk/Chunk', 'java/util/Random', 'net/minecraft/util/math/BlockPos$Mutable', top, top, 'net/minecraft/block/BlockState' }
    stack: { 'net/minecraft/world/gen/carver/Carver', 'net/minecraft/block/BlockState' }
  Bytecode:
    0x0000000: 2db6 00bb 1505 a100 0503 ac2b 2db9 00c1
    0x0000010: 0200 3a06 2a19 06b6 00c7 9a00 0503 ac2d
    0x0000020: b600 bb10 0aa0 0046 2cb6 00cd 3807 1707
    0x0000030: 8d14 00ce 989c 0025 2b2d b200 d2b6 00d6
    0x0000040: 03b9 00da 0400 572b b900 de01 002d b200
    0x0000050: d203 b900 e404 00a7 0012 2b2d b200 7ab6
    0x0000060: 00d6 03b9 00da 0400 5704 ac2d b600 bb10
    0x0000070: 0aa2 0014 2b2d b200 77b6 00d6 03b9 00da
    0x0000080: 0400 5703 ac2b 2db2 00e7 b600 eb03 b900
    0x0000090: da04 0057 04ac                         
  Stackmap Table:
    chop_frame(@11,2)
    full_frame(@31,{Top,Object[#189],Object[#201],Object[#7]},{})
    full_frame(@90,{Top,Object[#189],Top,Object[#7]},{})
    full_frame(@105,{},{})
    full_frame(@107,{Top,Object[#189],Top,Object[#7]},{})
    same_frame(@133)

	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver.java:33)
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers.java:19)
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries.java:45)
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:75)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:74)
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:266)
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:44)
	at de.bixilon.pixlyzer.PixLyzer.main(PixLyzer.kt:69)
```

**Comment by sfPlayer1** [comment]
check-/fixPackageAccess currently only verifies/fixes accessibility to the target member in field and method invocations, so this is a bug/limitation in TR.

I'll look into extending it, thanks for the report!

**Comment by sfPlayer1** [comment]
Does https://files.player.to/tmp/tiny-remapper-0.3.1-fat-player.jar fix it?

**Comment by Bixilon** [comment]
Yes, it does. Both errors are gone and it runs with byte code checking. Many thanks!

I'll leave this issue opened now, because it only works on the hacked version, not on master (so feel free to close it when you are done)

PS: First I wanted to use MCP, but it did not work and I opened an issue:

![Screenshot_20210323_232719](https://user-images.githubusercontent.com/26258520/114168745-327d2e80-9920-11eb-95e8-c0368c401e20.png)


So I'd say the fabric community is way more polite and the way to go :)

**Comment by sfPlayer1** [comment]
The related change is in the remapbridges branch now, merge pending some unrelated changes.

**Comment by Bixilon** [comment]
@sfPlayer1 having a problem: 

```
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unsupported class file major version 60
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:431)
	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:65)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:418)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:414)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2876)
	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:414)
	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:65)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:383)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:379)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	... 3 more
```

(Havn't cheked master), but it looks like, that your secret patch is not working with the newest snapshot (21w19a), because they use Java 16 now. Can you send me another super secret version Or is master working now?

Thanks

**Comment by sfPlayer1** [comment]
It is in the remapbridges branch, just build that (may have to bump the asm lib version there to 9.1)

**Comment by Bixilon** [comment]
Thanks, worked!

**Comment by LogicFan** [comment]
I guess this issue can be closed, @sfPlayer1?
