### ISSUE TITLE
Remapping fails when having annotated record component

### ISSUE THREAD

**Issue by derklaro** [FabricMC/tiny-remapper#82]
For example add create a record like:
```java
public record NetworkPlayerProxyInfo(
  @NonNull UUID uniqueId,
  @NonNull String name,
  @Nullable String xBoxId,
  @Range(from = 47, to = Integer.MAX_VALUE) int version,
  @NonNull HostAndPort address,
  @NonNull HostAndPort listener,
  boolean onlineMode,
  @NonNull NetworkServiceInfo networkService
) implements Cloneable {
```

and build the project. The jar remapping will fail when trying to resolve the annotation record name with:
```
[gradle call stack removed]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Deprecated function
	at net.fabricmc.tinyremapper.TinyRemapper.waitForAll(TinyRemapper.java:1164)
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:906)
	at net.fabricmc.loom.task.RemapJarTask$RemapAction.remap(RemapJarTask.java:244)
	at net.fabricmc.loom.task.RemapJarTask$RemapAction.execute(RemapJarTask.java:222)
	... 24 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Deprecated function
	at net.fabricmc.tinyremapper.TinyRemapper.waitForAll(TinyRemapper.java:1161)
	... 27 more
Caused by: java.lang.RuntimeException: Deprecated function
	at net.fabricmc.tinyremapper.AsmRemapper.mapAnnotationAttributeName(AsmRemapper.java:143)
	at org.objectweb.asm.commons.AnnotationRemapper.mapAnnotationAttributeName(AnnotationRemapper.java:212)
	at org.objectweb.asm.commons.AnnotationRemapper.visit(AnnotationRemapper.java:117)
	at org.objectweb.asm.ClassReader.readElementValue(ClassReader.java:3051)
	at org.objectweb.asm.ClassReader.readElementValues(ClassReader.java:2993)
	at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:1030)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:731)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:1071)
	at net.fabricmc.tinyremapper.TinyRemapper.lambda$apply$5(TinyRemapper.java:902)
```

When removing the annotations from the record the compile process works as intended.

Related code:
https://github.com/FabricMC/tiny-remapper/blob/2bf2d78219a568e8c87b36d3ed95438b97d4f180/src/main/java/net/fabricmc/tinyremapper/AsmRemapper.java#L141-L144

**Comment by sfPlayer1** [comment]
Thanks for the report, https://github.com/FabricMC/tiny-remapper/commit/52b25032a71a6d303dafa70184e21fb54c95789e should fix it, any way for you to verify?

**Comment by derklaro** [comment]
Works now as expected, thanks!
